//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brokerage_Plugins.Repositories.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Farabi_Plugins.Resources.PluginResource", typeof(PluginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activityparty.
        /// </summary>
        internal static string ActivityParty_LogicalName {
            get {
                return ResourceManager.GetString("ActivityParty_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partyid.
        /// </summary>
        internal static string ActivityParty_PartyId {
            get {
                return ResourceManager.GetString("ActivityParty_PartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_approvedamount.
        /// </summary>
        internal static string Case_ApprovedAmount {
            get {
                return ResourceManager.GetString("Case_ApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casecategory.
        /// </summary>
        internal static string Case_CaseCategory {
            get {
                return ResourceManager.GetString("Case_CaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticketnumber.
        /// </summary>
        internal static string Case_CaseNumber {
            get {
                return ResourceManager.GetString("Case_CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casesubcategory.
        /// </summary>
        internal static string Case_CaseSubCategory {
            get {
                return ResourceManager.GetString("Case_CaseSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casetypecode.
        /// </summary>
        internal static string Case_CaseType {
            get {
                return ResourceManager.GetString("Case_CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid.
        /// </summary>
        internal static string Case_Customer {
            get {
                return ResourceManager.GetString("Case_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incident.
        /// </summary>
        internal static string Case_LogicalName {
            get {
                return ResourceManager.GetString("Case_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ownerid.
        /// </summary>
        internal static string Case_Owner {
            get {
                return ResourceManager.GetString("Case_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_requestamount.
        /// </summary>
        internal static string Case_RequestAmount {
            get {
                return ResourceManager.GetString("Case_RequestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_symbol.
        /// </summary>
        internal static string Case_Symbol {
            get {
                return ResourceManager.GetString("Case_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casesubcategoryid.
        /// </summary>
        internal static string CaseSubCategory_Id {
            get {
                return ResourceManager.GetString("CaseSubCategory_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casesubcategoriesid.
        /// </summary>
        internal static string CaseSubCategory_LinkId {
            get {
                return ResourceManager.GetString("CaseSubCategory_LinkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casesubcategory.
        /// </summary>
        internal static string CaseSubCategory_LogicalName {
            get {
                return ResourceManager.GetString("CaseSubCategory_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createdon.
        /// </summary>
        internal static string CreateOn {
            get {
                return ResourceManager.GetString("CreateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_approvedamount.
        /// </summary>
        internal static string MarginLoan_ApprovedAmount {
            get {
                return ResourceManager.GetString("MarginLoan_ApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_incidentid.
        /// </summary>
        internal static string MarginLoan_Case {
            get {
                return ResourceManager.GetString("MarginLoan_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_marginloan.
        /// </summary>
        internal static string MarginLoan_LogicalName {
            get {
                return ResourceManager.GetString("MarginLoan_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_requestamount.
        /// </summary>
        internal static string MarginLoan_RequestAmount {
            get {
                return ResourceManager.GetString("MarginLoan_RequestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_symbolname.
        /// </summary>
        internal static string MarginLoan_Symbol {
            get {
                return ResourceManager.GetString("MarginLoan_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_sla_activation_1.
        /// </summary>
        internal static string SlaCategory_Activation1 {
            get {
                return ResourceManager.GetString("SlaCategory_Activation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_sla_activation_2.
        /// </summary>
        internal static string SlaCategory_Activation2 {
            get {
                return ResourceManager.GetString("SlaCategory_Activation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_sla_activation_3.
        /// </summary>
        internal static string SlaCategory_Activation3 {
            get {
                return ResourceManager.GetString("SlaCategory_Activation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_duration1.
        /// </summary>
        internal static string SlaCategory_Duration1 {
            get {
                return ResourceManager.GetString("SlaCategory_Duration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_duration2.
        /// </summary>
        internal static string SlaCategory_Duration2 {
            get {
                return ResourceManager.GetString("SlaCategory_Duration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_duration3.
        /// </summary>
        internal static string SlaCategory_Duration3 {
            get {
                return ResourceManager.GetString("SlaCategory_Duration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_slacategory.
        /// </summary>
        internal static string SlaCategory_LogicalName {
            get {
                return ResourceManager.GetString("SlaCategory_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string Sms_Description {
            get {
                return ResourceManager.GetString("Sms_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_sms.
        /// </summary>
        internal static string Sms_LogicalName {
            get {
                return ResourceManager.GetString("Sms_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regardingobjectid.
        /// </summary>
        internal static string Sms_Regarding {
            get {
                return ResourceManager.GetString("Sms_Regarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_template.
        /// </summary>
        internal static string Sms_SmsTemplate {
            get {
                return ResourceManager.GetString("Sms_SmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        internal static string Sms_Subject {
            get {
                return ResourceManager.GetString("Sms_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string SMS_To {
            get {
                return ResourceManager.GetString("SMS_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_smstemplate.
        /// </summary>
        internal static string SmsTemplates_LogicalName {
            get {
                return ResourceManager.GetString("SmsTemplates_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_name.
        /// </summary>
        internal static string SmsTemplates_Name {
            get {
                return ResourceManager.GetString("SmsTemplates_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_smstemplatebody.
        /// </summary>
        internal static string SmsTemplates_Text {
            get {
                return ResourceManager.GetString("SmsTemplates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statuscode.
        /// </summary>
        internal static string StatusReason {
            get {
                return ResourceManager.GetString("StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systemuser.
        /// </summary>
        internal static string SystemUser_LogicalName {
            get {
                return ResourceManager.GetString("SystemUser_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_deadline.
        /// </summary>
        internal static string Task_Deadline {
            get {
                return ResourceManager.GetString("Task_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskdeadline1.
        /// </summary>
        internal static string Task_Deadline1 {
            get {
                return ResourceManager.GetString("Task_Deadline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskdeadline2.
        /// </summary>
        internal static string Task_Deadline2 {
            get {
                return ResourceManager.GetString("Task_Deadline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskdeadline3.
        /// </summary>
        internal static string Task_Deadline3 {
            get {
                return ResourceManager.GetString("Task_Deadline3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualdurationminutes.
        /// </summary>
        internal static string Task_Duration {
            get {
                return ResourceManager.GetString("Task_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string Task_LogicalName {
            get {
                return ResourceManager.GetString("Task_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ownerid.
        /// </summary>
        internal static string Task_Owner {
            get {
                return ResourceManager.GetString("Task_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regardingobjectid.
        /// </summary>
        internal static string Task_Regarding {
            get {
                return ResourceManager.GetString("Task_Regarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_slacategoryid.
        /// </summary>
        internal static string Task_SlaCategory {
            get {
                return ResourceManager.GetString("Task_SlaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statecode.
        /// </summary>
        internal static string Task_Status {
            get {
                return ResourceManager.GetString("Task_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        internal static string Task_Subject {
            get {
                return ResourceManager.GetString("Task_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskstep.
        /// </summary>
        internal static string Task_TaskStep {
            get {
                return ResourceManager.GetString("Task_TaskStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casecategory.
        /// </summary>
        internal static string TaskManager_CaseCategory {
            get {
                return ResourceManager.GetString("TaskManager_CaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_casesubcategory.
        /// </summary>
        internal static string TaskManager_CaseSubCategory {
            get {
                return ResourceManager.GetString("TaskManager_CaseSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_firsttaskstep.
        /// </summary>
        internal static string TaskManager_FirstStep {
            get {
                return ResourceManager.GetString("TaskManager_FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskmanagerid.
        /// </summary>
        internal static string TaskManager_Id {
            get {
                return ResourceManager.GetString("TaskManager_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskmanager.
        /// </summary>
        internal static string TaskManager_LogicalName {
            get {
                return ResourceManager.GetString("TaskManager_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskStep_CompletedMessage {
            get {
                return ResourceManager.GetString("TaskStep_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_completedstep.
        /// </summary>
        internal static string TaskStep_CompletedStep {
            get {
                return ResourceManager.GetString("TaskStep_CompletedStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskStep_CompletedTeam {
            get {
                return ResourceManager.GetString("TaskStep_CompletedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_completestatus.
        /// </summary>
        internal static string TaskStep_CompleteStatus {
            get {
                return ResourceManager.GetString("TaskStep_CompleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_duedate.
        /// </summary>
        internal static string TaskStep_DueDate {
            get {
                return ResourceManager.GetString("TaskStep_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskstep.
        /// </summary>
        internal static string TaskStep_LogicalName {
            get {
                return ResourceManager.GetString("TaskStep_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_message.
        /// </summary>
        internal static string TaskStep_Message {
            get {
                return ResourceManager.GetString("TaskStep_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskStep_Order {
            get {
                return ResourceManager.GetString("TaskStep_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_prosseccduration.
        /// </summary>
        internal static string TaskStep_ProsseccDuration {
            get {
                return ResourceManager.GetString("TaskStep_ProsseccDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_regardingstate.
        /// </summary>
        internal static string TaskStep_RegardingStatus {
            get {
                return ResourceManager.GetString("TaskStep_RegardingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_regardingstatusreason.
        /// </summary>
        internal static string TaskStep_RegardingStatusReason {
            get {
                return ResourceManager.GetString("TaskStep_RegardingStatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskStep_RejectedMessage {
            get {
                return ResourceManager.GetString("TaskStep_RejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_rejectedstep.
        /// </summary>
        internal static string TaskStep_RejectedStep {
            get {
                return ResourceManager.GetString("TaskStep_RejectedStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaskStep_RejectedTeam {
            get {
                return ResourceManager.GetString("TaskStep_RejectedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_rejectstatus.
        /// </summary>
        internal static string TaskStep_RejectStatus {
            get {
                return ResourceManager.GetString("TaskStep_RejectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_rejectstatusreason.
        /// </summary>
        internal static string TaskStep_RejectStatusReason {
            get {
                return ResourceManager.GetString("TaskStep_RejectStatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_sendsmstouser.
        /// </summary>
        internal static string TaskStep_SendSmsToUser {
            get {
                return ResourceManager.GetString("TaskStep_SendSmsToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_slacategoryid.
        /// </summary>
        internal static string TaskStep_SlaCategory {
            get {
                return ResourceManager.GetString("TaskStep_SlaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_smstemplate.
        /// </summary>
        internal static string TaskStep_SmsTemplate {
            get {
                return ResourceManager.GetString("TaskStep_SmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_taskmanager.
        /// </summary>
        internal static string TaskStep_TaskManager {
            get {
                return ResourceManager.GetString("TaskStep_TaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_team.
        /// </summary>
        internal static string TaskStep_Team {
            get {
                return ResourceManager.GetString("TaskStep_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_user.
        /// </summary>
        internal static string TaskStep_User {
            get {
                return ResourceManager.GetString("TaskStep_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_usersmstemplate.
        /// </summary>
        internal static string TaskStep_UserSmsTemplate {
            get {
                return ResourceManager.GetString("TaskStep_UserSmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team.
        /// </summary>
        internal static string Team_LogicalName {
            get {
                return ResourceManager.GetString("Team_LogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frb_completestatusreason.
        /// </summary>
        internal static string TeskStep_CompleteStatusReason {
            get {
                return ResourceManager.GetString("TeskStep_CompleteStatusReason", resourceCulture);
            }
        }
    }
}
